### ISSUE TITLE
Put fanout & express-lane queues on same machine

### ISSUE THREAD

**Issue by Simon-Harris-IBM** [Simon-Harris-IBM/ObjectNetChallenge-Workflows#15]
Makes sense to have these 2 on a single server

**Comment by Simon-Harris-IBM** [comment]
Will implement once we have one or two more machines on the backend

**Comment by thomasyu888** [comment]
So actually now that I think about it, here is how I think the configuration should be

1.  Small instance running main queue (the queue that participants submit to)
2.  One instance running the express lane queue (queue for testing)
3.  However many queues needed for the internal queues.

The reason for this is because the orchestrator has specific emails that it sends and each of these have different requirements for what the orchestrator should and shouldn't send.

**Comment by Simon-Harris-IBM** [comment]
Done.
We now have a small instance (non-GPU) running the main submission (fanout) Q and one queue per backend server...
