### ISSUE TITLE
Change output location from submitter_id to submitter user name

### ISSUE THREAD

**Issue by Simon-Harris-IBM** [Simon-Harris-IBM/ObjectNetChallenge-Workflows#28]
Currently, output files from the challenge go into the following directory structure:
 - 12345
 - 12345_LOCKED

Where '12345' is the submitter's synapse id.

Some of the feedback we had from MIT was this is confusing as the user does not know what their id number is. Is it possible to change the output folder such that the userid is replaced with userName ?

**Comment by thomasyu888** [comment]
@Simon-Harris-IBM . The reason we probably can't do this is because people can change their usernames, while the userId is unique.  Each line in the dashboard corresponds with the log folder of their submission. Participants will not see 12345_LOCKED unless we provide that link to them on the dashboard

**Comment by Simon-Harris-IBM** [comment]
Agreed. I think if we do a better job of arranging the wiki & dashboard we can hide these folders from participants simply by directing them directly to the files/folders.

Will keep this issue open as a reminder to re-arrange the wiki.

**Comment by Simon-Harris-IBM** [comment]
Fixed by issue #18
